name: Add Count

on:
  workflow_dispatch:
    inputs:
      count:
        description: "Add Count"
        type: number
        default: 1
jobs:
  add_count:
    runs-on: ubuntu-latest  
    steps:
      - uses: actions/checkout@v3
      - name: 
        run: |          
          chmod +x scripts/ssh.sh
          bash scripts/ssh.sh
          echo ${{ secrets.PRIVATE_KEY }} | tr -d '\r' > ~/.ssh/id_rsa
          chmod +x scripts/add.sh
          bash scripts/add.sh ${{ github.event.inputs.count }}
          chmod +x scripts/git.sh
          bash scripts/git.sh
        shell: bash
