name: Add Count

on:
  workflow_dispatch:
    inputs:
      count:
        description: "Add Count"
        type: number
        default: 1
jobs:
  add_count:
    runs-on: ubuntu-latest  
    steps:
      - uses: actions/checkout@v3
      - name: Add Count
        run: |
          chmod +x scripts/add.sh
          bash scripts/add.sh ${{ github.event.inputs.count }}
        shell: bash

      - name: Push changes using action
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
