name: Add Count

on:
  workflow_dispatch:
    inputs:
      count:
        description: "Add Count"
        type: number
        default: 1
jobs:
  add_count:
    runs-on: ubuntu-latest  
    steps:
      - uses: actions/checkout@v3
      - name: 
        run: |
          echo "The count is ${{ github.event.inputs.count }}"
          chmod +x add.sh
          bash add.sh ${{ github.event.inputs.count }}
        shell: bash
