name: Add Count

on:
  workflow_dispatch:
    inputs:
      count:
        description: "Add Count"
        default: 1
jobs:
  add_count:
    runs-on: ubuntu-latest  
    steps:
      - uses: actions/checkout@v3
      - name: 
        run: |
         chmod +x add.sh
         bash add.sh 1
        shell: bash
