name: Subtract Count

on:
  workflow_dispatch:
    inputs:
      count:
        description: "Subtract Count"
        type: number
        default: 1
jobs:
  sub_count:
    runs-on: ubuntu-latest  
    steps:
      - uses: actions/checkout@v3
      - name: Subtract Count
        run: |
          chmod +x scripts/sub.sh
          bash scripts/sub.sh ${{ github.event.inputs.count }}
        shell: bash

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
