name: Subtract Count

on:
  workflow_dispatch:
    inputs:
      count:
        description: "Subtract Count"
        type: number
        default: 1
jobs:
  sub_count:
    runs-on: ubuntu-latest  
    steps:
      - uses: actions/checkout@v3
      - name: 
        run: |
          ls -lah
          echo "The count is ${{ github.event.inputs.count }}"
          chmod +x sub.sh
          bash scripts/sub.sh ${{ github.event.inputs.count }}
        shell: bash
